### PR TITLE
Update and rename jplister.java to jplister

### PR DESCRIPTION
**Pull request by xenoterracide**

### CODE REVIEW

**Review by joshuacox — COMMENTED** [review]
yeah, I hear you xeno, but this is a comparison of java and python.  So you can't just take the binary name right now.  But I like the boldness here. Kindly rejected.  But I will take your changes to jplister.java.

**Comment by joshuacox** [comment]
if you like name it jplister-java or something similar

**Comment by xenoterracide** [comment]
Yeah it's not my limitation that it can't be named.java that's literally some strange thing that they imposed upon it for the #! Implementations. I'm going to bed but if you prefer -java and it runs go for it

**Comment by xenoterracide** [comment]
fixed, again, I don't know if this has chmod+x haven't cloned it locally

**Pull request merged**
